### ISSUE TITLE
We should add Travis

### ISSUE THREAD

**Issue by TheKing42** [danfiscus/factorpro#18]
https://travis-ci.org/

What it does is that anytime anyone commits or does a pull request, a remote server will test to see if our code compiles. It's easy to set up, and free. (Also, if we make any tests, it can run those as well.)

**Comment by TheKing42** [comment]
For an example, see https://github.com/ndmitchell/tagsoup/pull/30 (click the green checkmark).

**Comment by TheKing42** [comment]
Also, we can add the travis badge from http://shields.io/

**Comment by danfiscus** [comment]
That sounds really useful! Would you mind setting that up?
