### ISSUE TITLE
Text wrapping issues

### ISSUE THREAD

**Issue by danfiscus** [danfiscus/factorpro#19]
On Mac, the terminal is 80x24, and the text is wrapped to fit. This causes the following weird text flow:
![screen shot 2016-01-30 at 9 11 37 pm](https://cloud.githubusercontent.com/assets/8755783/12699774/3be97a2a-c796-11e5-9e64-6e62c782ee26.PNG)
I don't have access to Windows or Linux to check, but I think they have the same problem, I just don't know what the console size it. Could someone check and report back so I can manually wrap the text?

**Comment by TheKing42** [comment]
On linux, it depends on the size of your terminal window. Does Windows even have terminals :trollface:?
