### ISSUE TITLE
Factor listings "loop"

### ISSUE THREAD

**Issue by danfiscus** [danfiscus/factorpro#20]
When outputting factors, the output shows factor pairs twice, once as "x times y" then after halfway as "y times x". In order to only list each factor once, we should eliminate those duplicates.

**Comment by danfiscus** [comment]
Having some trouble fixing this one. My solution (divide the for loop limiter by 2) didn't work properly: 
![screen shot 2016-01-30 at 9 43 16 pm](https://cloud.githubusercontent.com/assets/8755783/12699862/7cdd00e8-c79a-11e5-8795-8852b3f612bd.PNG)
It doesn't stop when x and y flip. It stops halfway. Any ideas @TheKing42 ?

**Comment by TheKing42** [comment]
Compare x and y, and then break out of the loop. (Also, it is peculiar that didn't work. You could create a new branch that you could then delete later to share the code.)

**Comment by danfiscus** [comment]
Would you mind working on that while I set up travis?

**Comment by TheKing42** [comment]
`factorpro` isn't currently compiling on linux. I can try though.

**Comment by danfiscus** [comment]
Update your compiler to the latest version. stoi uses new C++ stuff to convert string to int
